"""
Token-Based RL State Module
============================

This module provides functionality for creating reinforcement learning states
from tokens generated by the classification and tokenization pipeline.
"""

import numpy as np
import torch
from typing import Dict, List, Tuple, Optional, Any


class TokenBasedRLState:
    """
    Class for creating and managing RL states from generated tokens
    """
    
    def __init__(self, token_data: Dict[str, np.ndarray]):
        """
        Initialize with token data from the pipeline
        
        Args:
            token_data: Dictionary containing tokens and metadata
        """
        self.tokens = token_data['tokens']
        self.labels = token_data['labels'].flatten() if token_data['labels'].ndim > 1 else token_data['labels']
        self.token_shape = token_data['token_shape']
        self.n_tokens = token_data['n_tokens']
        self.embedding_dim = token_data['embedding_dim']
        
        # Validate token data
        self._validate_token_data()
    
    def _validate_token_data(self):
        """Validate the token data structure"""
        if not isinstance(self.tokens, np.ndarray):
            raise ValueError("Tokens must be a numpy array")
        
        if self.tokens.ndim != 3:
            raise ValueError(f"Tokens must be 3D array, got {self.tokens.ndim}D")
        
        if len(self.tokens) != len(self.labels):
            raise ValueError("Number of token sequences must match number of labels")
    
    def create_rl_state_from_tokens(self, sequence_idx: int = 0) -> np.ndarray:
        """
        Convert tokens to a state representation for RL
        
        Args:
            sequence_idx: Index of the sequence to use
            
        Returns:
            State vector for RL algorithm
        """
        if sequence_idx >= len(self.tokens):
            raise ValueError(f"Sequence index {sequence_idx} out of range. Max: {len(self.tokens) - 1}")
        
        # Get the specific sequence
        sequence = self.tokens[sequence_idx]  # Shape: (seq_len, token_dim)
        
        # Flatten the sequence to create a state vector
        state = sequence.flatten()
        
        return state
    
    def create_trajectory_dataset(self) -> Dict[str, np.ndarray]:
        """
        Create a trajectory dataset for RL training
        
        Returns:
            Dictionary containing trajectories and actions
        """
        trajectories = []
        actions = []
        
        for i in range(len(self.tokens)):
            # Each sequence is a trajectory
            trajectory = self.tokens[i]  # Shape: (seq_len, token_dim)
            action = self.labels[i]      # The action label for this trajectory
            
            trajectories.append(trajectory)
            actions.append(action)
        
        # Convert to numpy arrays
        trajectories = np.array(trajectories)
        actions = np.array(actions)
        
        return {
            'trajectories': trajectories,
            'actions': actions,
            'n_trajectories': len(trajectories),
            'trajectory_length': trajectories[0].shape[0],
            'token_dim': trajectories[0].shape[1]
        }
    
    def create_rl_environment_states(self, window_size: int = 3) -> np.ndarray:
        """
        Create sliding window states for RL environment
        
        Args:
            window_size: Size of the sliding window
            
        Returns:
            Array of windowed states
        """
        all_states = []
        
        for sequence in self.tokens:
            # Create sliding windows
            for i in range(len(sequence) - window_size + 1):
                window = sequence[i:i+window_size]
                # Flatten the window
                state = window.flatten()
                all_states.append(state)
        
        states = np.array(all_states)
        return states
    
    def create_ppo_compatible_states(self) -> Dict[str, np.ndarray]:
        """
        Create states compatible with PPO algorithm
        
        Returns:
            Dictionary with PPO-compatible state-action pairs
        """
        trajectory_data = self.create_trajectory_dataset()
        trajectories = trajectory_data['trajectories']
        actions = trajectory_data['actions']
        
        # Create state-action pairs
        states = []
        for traj in trajectories:
            # Use the mean of the trajectory as state representation
            state = np.mean(traj, axis=0)
            states.append(state)
        
        states = np.array(states)
        
        return {
            'states': states,
            'actions': actions,
            'state_dim': states.shape[1],
            'action_dim': len(np.unique(actions))
        }
    
    def create_sac_compatible_states(self) -> Dict[str, np.ndarray]:
        """
        Create states compatible with SAC algorithm
        
        Returns:
            Dictionary with SAC-compatible state-action pairs
        """
        trajectory_data = self.create_trajectory_dataset()
        trajectories = trajectory_data['trajectories']
        actions = trajectory_data['actions']
        
        # Create continuous state representation
        states = []
        for traj in trajectories:
            # Use the full trajectory as state
            state = traj.flatten()
            states.append(state)
        
        states = np.array(states)
        
        # For SAC, we might want continuous actions
        # Convert discrete actions to continuous embeddings
        unique_actions = np.unique(actions)
        action_embeddings = []
        for action in actions:
            # Create one-hot encoding
            one_hot = np.zeros(len(unique_actions))
            # Find the index of the action in unique_actions
            action_idx = np.where(unique_actions == action)[0][0]
            one_hot[action_idx] = 1.0
            action_embeddings.append(one_hot)
        
        action_embeddings = np.array(action_embeddings)
        
        return {
            'states': states,
            'action_embeddings': action_embeddings,
            'state_dim': states.shape[1],
            'action_dim': action_embeddings.shape[1]
        }
    
    def create_hierarchical_states(self, hierarchy_levels: int = 2) -> Dict[str, np.ndarray]:
        """
        Create hierarchical state representations for hierarchical RL
        
        Args:
            hierarchy_levels: Number of hierarchy levels
            
        Returns:
            Dictionary with hierarchical states
        """
        trajectory_data = self.create_trajectory_dataset()
        trajectories = trajectory_data['trajectories']
        
        hierarchical_states = {}
        
        for level in range(hierarchy_levels):
            if level == 0:
                # Lowest level: full trajectory
                states = [traj.flatten() for traj in trajectories]
            else:
                # Higher levels: increasingly abstract representations
                states = []
                for traj in trajectories:
                    # Use different aggregation strategies for different levels
                    if level == 1:
                        # Level 1: mean and std of trajectory
                        state = np.concatenate([
                            np.mean(traj, axis=0),
                            np.std(traj, axis=0)
                        ])
                    else:
                        # Level 2+: statistical moments
                        state = np.concatenate([
                            np.mean(traj, axis=0),
                            np.std(traj, axis=0),
                            np.percentile(traj, [25, 50, 75], axis=0).flatten()
                        ])
                    states.append(state)
            
            hierarchical_states[f'level_{level}'] = np.array(states)
        
        return hierarchical_states
    
    def get_state_statistics(self) -> Dict[str, Any]:
        """Get statistics about the token states"""
        trajectory_data = self.create_trajectory_dataset()
        
        return {
            'n_sequences': len(self.tokens),
            'sequence_length': self.tokens.shape[1],
            'token_dimension': self.tokens.shape[2],
            'n_trajectories': trajectory_data['n_trajectories'],
            'trajectory_length': trajectory_data['trajectory_length'],
            'token_dim': trajectory_data['token_dim'],
            'action_distribution': np.bincount(self.labels),
            'unique_actions': np.unique(self.labels)
        }
    
    def save_rl_states(self, save_path: str):
        """Save RL states to file"""
        rl_data = {
            'ppo_states': self.create_ppo_compatible_states(),
            'sac_states': self.create_sac_compatible_states(),
            'hierarchical_states': self.create_hierarchical_states(),
            'statistics': self.get_state_statistics(),
            'original_tokens': self.tokens,
            'labels': self.labels
        }
        
        np.savez(save_path, **rl_data)
        print(f"RL states saved to: {save_path}")
