from __future__ import annotations
from abc import ABC, abstractmethod
import logging 
from typing import Dict, Optional, Tuple
import math
import torch
import torch.nn as nn
import torch.nn.functional as F
from einops import rearrange
from torch.distributions import Categorical
import os, sys
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from models.rl.vla.model.components.base import TokenGroup
from models.rl.vla.model.components.diffusion import cosine_beta_schedule, create_diffusion_model
from models.rl.vla.model.components.tokenizers import BinTokenizer
from models.rl.vla.model.components.transformer import MAPHead
from models.rl.vla.model.components.unet import ConditionalUnet1D, unet_squaredcos_cap_v2
from models.rl.vla.utils.typing import PRNGkey

def masked_mean(x: torch.Tensor, mask: torch.Tensor):
    mask = torch.broadcast_to(mask, x.shape)
    return torch.mean(x * mask) / torch.clamp(torch.mean(mask), min = 1e-5, max = None)

def continuous_loss(
        pred_value: torch.Tensor, ## output of continuous action head's with input of transformer output
        ground_truth_value: torch.Tensor, ## actions 
        mask: torch.Tensor, ### masks generated by timestep and action pad masks via broadcasting
        loss_type: str = 'mse'
):
    """
    Args:
        pred_value: shape(batch_dims...)
        ground_truth_value: continuous values with shape (batch_dims...)
        mask: broadcastable to ground_truth
    """

    if loss_type == 'mse':
        loss = torch.square(pred_value - ground_truth_value)

    elif loss_type == 'l1':
        loss = torch.abs(pred_value - ground_truth_value)

    else:
        raise ValueError(f'Invalid loss type: {loss_type}')
    
    loss = masked_mean(loss, mask)
    mse = torch.square(pred_value - ground_truth_value)
    mse = masked_mean(mse, mask)

    return loss, {
        'loss': loss,
        'mse': mse
    }

def discrete_loss(
        discrete_tokenizer: BinTokenizer,
        logits: torch.Tensor,
        ground_truth_value: torch.Tensor,
        mask: torch.Tensor
):
    """
    Args:
        discrete_tokenizer: BinTokenizer to use on ground_truth_value
        logits: shape (batch_dims..., vocab_size)
        ground_truth_value: continuous values in with shape (batch_dims..., )
        mask: broadcastable to ground_truth_value 
    """
    labels = discrete_tokenizer(ground_truth_value) ## Through BinTokenizer, making ground_truth_value into token values
    labels_one_hot = F.one_hot(labels, num_classes=logits.shape[-1]).to(logits.dtype)  ## only corresponding labels would be 1, otherwise 0

    logprobs = F.log_softmax(logits, dim=-1) ## shape of (batch_dims, vocab_size)
    nll = -(logprobs * labels_one_hot).sum(dim = -1) ### only maximum values remain
    loss = masked_mean(nll, mask)

    pred_label = logprobs.argmax(dim=-1)
    acc = masked_mean((pred_label == labels).to(logits.dtype), mask)

    pred_value = discrete_tokenizer.decode(pred_label).to(logits.dtype) ## decode predicted labels to value of probability
    mse = masked_mean(torch.square(pred_value - ground_truth_value), mask)

    return loss, {
        'loss': loss,
        'mse' : mse,
        'accuracy': acc
    }

class ActionHead(ABC, nn.Module):
    """
    Action Prediction modules that take in the transformer token outputs and predict actions 

    Each action head here does chunked action prediction: i.e. at every timestep, it tries to predict the next 
    'action horizon' actions into the future from that timestep. Setting 'action_horizon = 1' corresponds to 
    the typical action prediction setup.  
    """
    @abstractmethod
    def loss(
        self, 
        transformer_outputs: Dict[str, TokenGroup],
        actions: torch.Tensor,
        timestep_pad_mask: torch.Tensor,
        action_pad_mask: torch.Tensor,
        train: bool = True
    ):
        raise NotImplementedError
    
    @abstractmethod
    def predict_action(
        self, 
        transformer_outputs: Dict[str, TokenGroup],
        argmax: bool = False,
        sample_shape: Tuple[int, ...] = (),
        rng: Optional[PRNGkey] = None,
        temperature: float = 1.0,
        train: bool = False,
        embodiment_action_dim: Optional[int] = None
    ):
        raise NotImplementedError
    

class ContinuousActionHead(ActionHead):
    """
    Predicts continuous actions (as opposed to discretized)

    Continuous actions are predicted y tanh squashing the model output to [-max_action, max_action], and then
    optimized using a standard regression loss. 
    token_group.tokens: [Batch, horizon, n_tokens, token_dim ]

    You may create an embedding by either mean-pooling across tokens (use_map = False) or using multi-head
    attention pooling (use_map = True). It is recommended to use MAP when decoding from the observation token stream.
    """

    def __init__(
            self,
            readout_key: str,
            use_map: bool = False,
            action_horizon: int = 1,
            action_dim: int = 7,
            max_action: float = 5.0,
            loss_type: str = 'mse'
    ):
        super().__init__()
        self.readout_key = readout_key
        self.use_map = use_map
        self.action_horizon = action_horizon
        self.action_dim = action_dim
        self.max_action = max_action
        self.loss_type = loss_type

        if use_map:
            self.map_head = MAPHead(num_readout=1)
        self.mean_proj = nn.Linear(-1, -1, bias=True)
        self._built = False

    def _build(self, token_dim):
        self.mean_proj = nn.Linear(token_dim, self.action_horizon * self.action_dim)
        nn.init.xavier_uniform_(self.mean_proj.weight)
        nn.init.zeros_(self.mean_proj.bias)
        self._built = True

    def forward(self, transformer_outputs: Dict[str, TokenGroup], train: bool = True):
        token_group = transformer_outputs[self.readout_key]

        assert token_group.tokens.ndim == 4, (
            f'Expected token_group.tokens to have shape (batch_size, window_size, num_tokens, embedding_size), '
            f'but got shape {token_group.tokens.shape}'
        )

        B, horizon, num_tokens, token_dim = token_group.shape
        if not self._built:
            self._build(token_dim)

        if self.use_map: ### Multi-head attention pooling
            embeddings = self.map_head(token_group, train = train)[:, :, 0, :]  ### shape is [B, horizon, token_dim], 

        else:
            embeddings = token_group.tokens.mean(dim = -2) ## taking mean over num_tokens 
        ## now embeddings is (batch_size, window_size, embedding_size)

        mean = self.mean_proj(embeddings) ## [B, horizon, action_horizon * action_dim]
        mean = rearrange(mean, 'b t (h a) -> b t h a', h = self.action_horizon, a = self.action_dim)
        mean = torch.tanh(mean / self.max_action) * self.max_action
        return mean 

    def loss(
            self, 
            transformer_output: Dict[str, TokenGroup],
            actions: torch.Tensor,
            timestep_pad_mask: torch.Tensor,
            action_pad_mask: torch.Tensor,
            train: bool = True
    ):
        """
        Computes the loss for the action regression objective.

        Args:
            transformer_outputs: must contain self.readout_key with shape (batch_size, window_size, num_tokens, embedding_size)
            actions: shape (batch_size, window_size, action_horizon, action_dim)
            timestep_pad_mask: boolean array (batch, window_size) which is true if the timestep is not a padding timestep
            action_pad_mask: boolean array (same shape as actions) which is True if the action dimension is not a padding dimension

        Returns:
            loss: float
            metrics: dict
        """

        mean = self.forward(transformer_output, train = train)
        mask = (timestep_pad_mask[:, :, None, None] & action_pad_mask) ### None argument is same as unsqueeze
        loss, metrics = continuous_loss(mean, actions, mask, loss_type=self.loss_type)
        loss = loss * self.action_dim
        metrics['loss'] *= self.action_dim
        metrics['mse'] *= self.action_dim

        return loss, metrics
    
    def predict_action(
            self, 
            transformer_outputs: Dict[str, TokenGroup],
            train: bool = True,
            *args,
            sample_shape: tuple = (),
            **kwargs,
    ):
        """
        Convenience methods for predicting actions for the final timestep in the window
        """
        ## only gets the last timestep in the window 
        mean = self.forward(transformer_outputs, train=train)[:, -1] ## [batch, 1(last timestep), action_horizon, action_dim]
        return torch.broadcast_to(mean, sample_shape + mean.shape)
    

class DiscreteActionHead(ActionHead):
    """
    A basic action decoding head that predicts discretized action using the transformer token embeddings.

    self.token_per determines how many tokens are used to represent each action.
        - If ""(empty string): then a single token is responsible for producing the action logits
            for all dimensions at all future prediction horizons
        - If "action_horizon", then we use 'self.action_horizon' tokens, each responsible for producing the action logits
            for all dimensions at the corresponding future prediction horizon
        - If "action_dim_and_action_horizon", then we use 'self.action_horizon * self.action_dim' tokens, where 
            each token is responsible for the logits for the specific dim and timestep

    If multi-head attention pooling is used (use_map = True), then the correct number of tokens is automatically 
    created, otherwise readout_key must have exactly the right number of tokens
    """

    def __init__(
            self, 
            readout_key: str,
            use_map: bool = False,
            token_per: str = 'action_dim_and_action_horizon',
            action_horizon: int = 1,
            action_dim: int = 7,
            vocab_size: int = 256,
            normalization_type: str = 'uniform'
    ):
        super().__init__()
        self._built = False

    def _build(self, token_dim):
        self._built = True
    
    def forward(self, transformer_output: Dict[str, TokenGroup], train: bool):
        return 
    
    def loss(
            self, 
            transformer_output: Dict[str, TokenGroup],
            action: torch.Tensor,
            timestep_pad_mask: torch.Tensor,
            action_pad_mask: torch.Tensor,
            train: bool = True
    ):
        action_logits = self.forward(transformer_output, train= train)

    def predict_action(
            self, 
            transformer_output: Dict[str, TokenGroup],
            train: bool = True,
            argmax: bool = False,
            sample_shape: tuple = (),
            rng: Optional[PRNGkey] = None,
            temperature: float = 1.0,
            **unused_kwargs, 
    ):
        """
        Convenience methods for predicting actions for the final timestep in the window
        """

class DiffusionActionHead(ActionHead):
    """
    Predicts actions uses a diffusion process.

    Only a single pass through the transformer is done to obtain an action embedding at each timestep. The
    actions are then predicted using a diffusion process conditioned on this embedding. The diffusion model
    architecture is an MLP with residual connections (see 'vla.model.components.diffusion').

    You may create an embedding by either mean-pooling across tokens (use_map = False) or using multi-head 
    attention pooling (use_map = True). It is recommended to use MAP when decoding from the observation token 
    stream. 

    Denoising diffusion over flattened actions conditioned on per-timestep embeddings. 
    Uses MLP ResNet score network from 'create_diffusion_model'
    """
    def __init__(
        self, 
        readout_key: str,
        use_map: bool = False,
        action_horizon: int = 1,
        action_dim: int = 7,
        max_action: float = 5.0,
        loss_type: str = 'mse',
        ## diffusion
        time_dim: int = 32,
        num_blocks: int = 3,
        dropout_rate: float = 0.0,
        hidden_dim: int = 256,
        use_layer_norm: bool = True,
        diffusion_steps: int = 20,
        n_diffusion_sample: int = 1
    ):
        super().__init__()
        self.readout_key = readout_key
        self.use_map = use_map
        self.action_horizon = action_horizon
        self.action_dim = action_dim
        self.max_action = max_action
        self.loss_type = loss_type

        self.time_dim = time_dim
        self.num_blocks = num_blocks
        self.dropout_rate = dropout_rate
        self.hidden_dim = hidden_dim
        self.use_layer_norm = use_layer_norm
        self.diffusion_steps = diffusion_steps
        self.n_diffusion_sample = n_diffusion_sample

        if self.use_map:
            self.map_head = MAPHead(num_readout=1)  ### returns (batch_size, num_readouts, token_dim)

        self.diffusion_model = create_diffusion_model(
            out_dim=self.action_dim,
            time_dim=self.time_dim,
            num_blocks=self.num_blocks,
            dropout_rate=self.dropout_rate,
            hidden_dim=self.hidden_dim,
            use_layer_norm=self.use_layer_norm
        )

        betas = cosine_beta_schedule(timesteps=self.diffusion_steps).float()
        self.register_buffer('betas', betas)
        self.register_buffer('alphas', 1 - betas)
        self.register_buffer('alpha_hats', torch.cumprod(betas, dim = 0))

    def _embed(self, token_group: TokenGroup, train: bool):
        if self.use_map:
            return self.map_head(token_group, train = train)[:, :, 0, :] ## [batch, time_dim, token_dim]
        return token_group.tokens.mean(dim = -2)  ## [batch, time_dim, token_dim]
    
    def forward(
            self, 
            transformer_output: Dict[str, TokenGroup],
            time: Optional[torch.Tensor] = None,
            noisy_actions: Optional[torch.Tensor] = None,
            train: bool = True
    ):
        """
        Performs a single forward pass through the diffusion model
        """
        token_group = transformer_output[self.readout_key]

        assert token_group.tokens.ndim == 4, (
            f'Expected token_group.tokens to have shape (batch_size, window_size, num_tokens, embedding_size),'
            f'but got shape {token_group.tokens.shape}'
        )

        if self.use_map: ## multi-head attention pooling
            embeddings = self.map_head(token_group, train = train)[:, :, 0]
